name: Sauce Demo automation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:        

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
            - uses: actions/checkout@v4
            

