name: Sauce Demo automation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:        

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run robot framework tests
              run: |
                mkdir -p results
                robot --outputdir results --variable BROWSER:headlesschrome tests/

            - name: Upload test reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: Robot test reports
                path: results/
                retention-days: 7

            - name: Generate GitHub Pages HTML report
              run: |
                # Check if output.xml exists
                echo "Checking if output.xml exists..."
                ls results/
                if [ -f results/output.xml ]; then
                  echo "output.xml found, generating report.html..."
                  rebot --outputdir results --report results/report.html results/output.xml
                else
                  echo "output.xml not found!"
                  exit 1
                fi

            - name: Upload test reports to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./results
                destination_dir: /test-reports
                user_name: "GitHub Actions"
                user_email: "actions@github.com"
              if: always()